=== slowpokes/webasyst-framework/wa-content/xml/wa-app-theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT theme (name+,description*,files*,about*, settings?)>
<!ATTLIST theme
	id CDATA #REQUIRED
	system (1|0) "0"
	vendor CDATA #IMPLIED
	author CDATA #IMPLIED
	app CDATA #REQUIRED
	parent_theme_id CDATA #IMPLIED
	version CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	locale CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description
	locale CDATA #REQUIRED
>
<!ELEMENT files (file+)>
<!ELEMENT file (description*)>
<!ATTLIST file
	path CDATA #REQUIRED
	custom (1|0) "0"
	parent (1|0) "0"
>
<!ELEMENT about (#PCDATA)>
<!ATTLIST about
	locale CDATA #REQUIRED
>
<!ELEMENT settings (setting+)>
<!ELEMENT setting (name+,description*,options?)>

<!ATTLIST setting
        var CDATA #REQUIRED
        value CDATA #IMPLIED
        control_type ("text"|"select"|"checkbox") "text"

>
<!ELEMENT options (option+)>
<!ELEMENT option (name*)>
<!ATTLIST option
        value CDATA #IMPLIED
>

=== slowpokes/webasyst-framework/wa-apps/site/themes/topshop/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd" >
<theme id="topshop" system="0" vendor="898299" author="wa-magazin.ru" app="site" version="1.0" parent_theme_id="shop:topshop">
    <name locale="en_US">Themes TopShop for Site</name>
    <name locale="ru_RU">Тема «TopShop» для Сайт</name>
    <description locale="en_US">Adaptive design theme TopShop</description>
    <description locale="ru_RU">Адаптивная тема «TopShop»</description>
    <files>
        <file path="index.html" parent="1">
            <description locale="en_US">Common layout</description>
            <description locale="ru_RU">Основной макет</description>
        </file>
        <file path="head.html">
            <description locale="en_US">Head file</description>
            <description locale="ru_RU">Файл для вставки в head</description>
        </file>
        <file path="breadcrumb.html">
            <description locale="en_US">Breadcrumbs</description>
            <description locale="ru_RU">Хлебные крошки</description>
        </file>
        <file path="page.html">
            <description locale="en_US">Page content</description>
            <description locale="ru_RU">Содержимое страницы</description>
        </file>
        <file path="footer.html" parent="1">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="my.profile.html" parent="1">
            <description locale="en_US">Customer account interface: contact info editing form</description>
            <description locale="ru_RU">Личный кабинет покупателя: редактирование контактной информации</description>
        </file>
        <file path="login.html" parent="1">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="forgotpassword.html" parent="1">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="signup.html" parent="1">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="main.html">
            <description locale="en_US">Content page</description>
            <description locale="ru_RU">Главная страница для вывода контетна</description>
        </file>
        <file path="error.html">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
    </files>
    <about locale="en_US"></about>
    <about locale="ru_RU">Универсальное семейство тем дизайна "TopShop" для базовых приложений фреймворка Вебасист:
        Сайт, Блог, Фото, Shop-Script и других. Темы дизайна "TopShop" оптимизированы для всех современных браузеров,
        планшетных компьютеров и мобильных устройств на основе iOS и Android.
    </about>
    <locales>
        <locale>
            <msgid>Tags</msgid>
            <msgstr locale="ru_RU">Теги</msgstr>
        </locale>
    </locales>
</theme>

=== slowpokes/webasyst-framework/wa-apps/site/themes/mmtt/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="mmtt" system="0" vendor="bd9" author="Vadim" app="site" version="1.1.1">
  <name locale="en_US">1mmtt.ru</name>
  <name locale="ru_RU">1mmtt.ru</name>
  <description locale="ru_RU">no</description>
  <files>
    <file path="index.html" custom="0">
    </file>
      <file path="header.html" custom="0">
      </file>
    </files>
  <about locale="en_US">
<![CDATA[
]]>
  </about>
  <about locale="ru_RU">
<![CDATA[
]]>
  </about>
</theme>

=== slowpokes/webasyst-framework/wa-apps/site/themes/ascetic/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd" >
<theme id="ascetic" system="1" vendor="webasyst" author="Webasyst" app="site" version="1.1.1">
  <name locale="en_US">Ascetic (Default 1.0)</name>
  <name locale="ru_RU">Аскетик (Default 1.0)</name>
  <files>
    <file path="index.html">
      <description locale="en_US">Common layout</description>
      <description locale="ru_RU">Основной макет</description>
    </file>
    <file path="ascetic.css">
      <description locale="en_US">Core CSS file</description>
      <description locale="ru_RU">Основной файл CSS-стилей</description>
    </file>
    <file path="mobile.css">
      <description locale="en_US">Additional CSS for multi-touch mobile devices</description>
      <description locale="ru_RU">Дополнительный CSS для мобильных устройств</description>
    </file>
    <file path="page.html">
      <description locale="en_US">Page content</description>
      <description locale="ru_RU">Содержимое страницы</description>
    </file>
    <file path="sidebar.html">
      <description locale="en_US">Page navigation sidebar</description>
      <description locale="ru_RU">Колонка с навигацией по страницам</description>
    </file>
    <file path="login.html">
		<description locale="en_US">Login page</description>
		<description locale="ru_RU">Страница входа для пользователей</description>
	</file>
    <file path="signup.html">
        <description locale="en_US">Sign up page</description>
        <description locale="ru_RU">Страница регистрации пользователей</description>
    </file>
    <file path="forgotpassword.html">
        <description locale="en_US">Forgot password page</description>
        <description locale="ru_RU">Страница сброса пароля</description>
    </file>
    <file path="error.html">
      <description locale="en_US">404 and other errors</description>
      <description locale="ru_RU">404 и другие ошибки</description>
    </file>
     <file path="my.profile.html">
        <description locale="en_US">My profile: contact info editing form</description>
        <description locale="ru_RU">Мой профиль: редактирование контактной информации</description>
    </file>
     <file path="my.nav.html">
        <description locale="en_US">My profile navigation</description>
        <description locale="ru_RU">Навигационное меню внутри личного кабинета</description>
    </file>
  </files>
  <settings>
    <setting var="nav_bg_color" control_type="color">
        <value>#000000</value>
        <name locale="en_US">Top navigation menu background color</name>
        <name locale="ru_RU">Цвет фона верхнего навигационного меню</name>
    </setting>
    <setting var="nav_text_color" control_type="color">
        <value>#CCCCCC</value>
        <name locale="en_US">Top navigation menu text color</name>
        <name locale="ru_RU">Цвет ссылок в верхнем навигационном меню</name>
    </setting>
  </settings>
</theme>

=== slowpokes/webasyst-framework/wa-apps/site/themes/aromateca/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="aromateca" system="0" vendor="bd9" author="Vadim" app="site" version="1.0">
    <name locale="en_US">aromateca.ru</name>
    <name locale="ru_RU">aromateca.ru</name>
    <description locale="ru_RU">no</description>
    <files>
        <file path="index.html" custom="0">
        </file>
        <file path="header.html" custom="0">
        </file>
    </files>
    <about locale="en_US">
        <![CDATA[
                ]]>
    </about>
    <about locale="ru_RU">
        <![CDATA[
                ]]>
    </about>
</theme>

=== slowpokes/webasyst-framework/wa-apps/blog/themes/topshop/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="topshop" system="0" vendor="898299" author="wa-magazin.ru" app="blog" parent_theme_id="shop:topshop" version="1.0">
  <name locale="en_US">Themes TopShop for Blog</name>
  <name locale="ru_RU">Тема «TopShop» для Блог</name>
  <description locale="en_US">Adaptive design theme TopShop</description>
  <description locale="ru_RU">Адаптивная тема «TopShop»</description>
  <files>
    <file path="index.html" parent="1"/>
    <file path="blog.js" custom="0"/>
    <file path="comment.html" custom="0">
      <description locale="en_US">One comment template</description>
      <description locale="ru_RU">Вывод одного комментария из списка</description>
    </file>
    <file path="comments.html" custom="0">
      <description locale="en_US">Post comment list</description>
      <description locale="ru_RU">Комментарии к записи блога</description>
    </file>
    <file path="head.html" custom="0">
      <description locale="en_US">Blog app's &lt;head&gt; instructions</description>
      <description locale="ru_RU">Блок &lt;head&gt; приложения «Блог»</description>
    </file>
    <file path="main.html">
      <description locale="en_US">Main layout</description>
      <description locale="ru_RU">Основное макет вывода содержимого и навигации в приложении «Блог»</description>
    </file>
    <file path="error.html" custom="0">
      <description locale="en_US">Error page</description>
      <description locale="ru_RU">Страница ошибки</description>
    </file>
    <file path="page.html" custom="0">
      <description locale="en_US">Static info page</description>
      <description locale="ru_RU">Информационная страница</description>
    </file>
    <file path="stream.html" custom="0">
      <description locale="en_US">Post stream wrapper</description>
      <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
    </file>
    <file path="stream_search.html" custom="0">
      <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
      <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
    </file>
    <file path="stream_posts.html" custom="0">
      <description locale="en_US">Default post list view mode</description>
      <description locale="ru_RU">Основной вид списка записей блога</description>
    </file>
    <file path="post.html" custom="0">
      <description locale="en_US">Dedicated post page</description>
      <description locale="ru_RU">Страница одной записи блога</description>
    </file>
    <file path="post.album.html" custom="0">
      <description locale="en_US">Photo album attached to the blog post</description>
      <description locale="ru_RU">Фотоальбом, прикрепленный к записи в блоге</description>
    </file>
    <file path="my.nav.html">
      <description locale="en_US">Customer account navigation menu</description>
      <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
    </file>
    <file path="login.html" parent="1">
        </file>
    <file path="signup.html" parent="1">
        </file>
    <file path="forgotpassword.html" parent="1">
        </file>
    <file path="my.profile.html" parent="1">
        </file>
    </files>
  <about locale="en_US"/>
  <about locale="ru_RU">Универсальное семейство тем дизайна "TopShop" для базовых приложений фреймворка Вебасист:
    Сайт, Блог, Фото, Shop-Script и других. Темы дизайна "TopShop" оптимизированы для всех современных браузеров,
    планшетных компьютеров и мобильных устройств на основе iOS и Android.
  </about>
</theme>

=== slowpokes/webasyst-framework/wa-apps/blog/themes/facebook/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="facebook" system="0" vendor="webasyst" author="Webasyst" app="blog" parent_theme_id="site:facebook" version="1.1.4">
    <name locale="en_US">Facebook</name>
    <name locale="ru_RU">Фейсбук</name>
    <files>
        <file path="facebook.blog.css" custom="0">
            <description locale="en_US">Core Blog app CSS</description>
            <description locale="ru_RU">Основной CSS приложения «Блог»</description>
        </file>      
        <file path="content.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Blog app content</description>
            <description locale="ru_RU">Основное макет вывода содержимого и навигации в приложении «Блог»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Blog app's &lt;head&gt; instructions</description>
            <description locale="en_US">Блок &lt;head&gt; приложения «Блог»</description>
        </file>
        <file path="stream.html" custom="0">
            <description locale="en_US">Post stream wrapper</description>
            <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
        </file>
        <file path="stream_search.html" custom="0">
            <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
            <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
        </file>
        <file path="stream_posts.html" custom="0">
            <description locale="en_US">Default post list view mode</description>
            <description locale="ru_RU">Основной вид списка записей блога</description>
        </file>
        <file path="post.html" custom="0">
            <description locale="en_US">Dedicated post page</description>
            <description locale="ru_RU">Страница одной записи блога</description>
        </file>
        <file path="post.album.html" custom="0">
            <description locale="en_US">Photo album attached to the blog post</description>
            <description locale="ru_RU">Фотоальбом, прикрепленный к записи в блоге</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static info page</description>
            <description locale="ru_RU">Информационная страница</description>
        </file>
        <file path="comments.html" custom="0">
            <description locale="en_US">Post comment list</description>
            <description locale="ru_RU">Комментарии к записи блога</description>
        </file>
        <file path="comment.html" custom="0">
            <description locale="en_US">One comment template</description>
            <description locale="ru_RU">Вывод одного комментария из списка</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="error.html" parent="1">
        </file>
        <file path="navigation.html" custom="0">
            <description locale="en_US">Internal app navigation</description>
            <description locale="ru_RU">Внутренняя навигация приложения</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="searchform.html" custom="0">
            <description locale="en_US">Internal app search form</description>
            <description locale="ru_RU">Форма поиска в приложении</description>
        </file>
        <file path="index.html" custom="0" parent="1">
        </file>
        <file path="facebook.css" custom="0" parent="1">
        </file>
        <file path="facebook.js" custom="0" parent="1">
        </file>
        <file path="facebook.blog.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>Facebook</b> design themes are designed for embedding Webasyst-powered websites into <a href="http://www.facebook.com">Facebook</a> social network as iframe apps. Facebook theme family is universal — there is a theme for every basic Webasyst app: Site, Blog, Photos, Shop-Script, etc. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Facebook theme for the Site application. All Facebook design themes for other apps (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p>Темы <b>Facebook</b> разработаны для внедрения сайтов, созданных на основе фреймворка Вебасист, в «<a href="http://www.facebook.com">Фейсбук</a>» в виде iframe-приложений. Семейство тем Facebook универсальное — подходит для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема для приложения «Сайт». Все темы Facebook для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
]]>
    </about>    
</theme>

=== slowpokes/webasyst-framework/wa-apps/mailer/themes/dsv2/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="dsv2" system="1" vendor="988467" author="Designsovkusom" app="mailer" parent_theme_id="site:dsv2" version="2.5.0">
    <name locale="en_US">Design with taste 2</name>
    <name locale="ru_RU">Дизайн со вкусом 2</name>
    <files>
        <file path="my.subscriptions.html">
            <description locale="en_US">Subscriptions home page</description>
            <description locale="ru_RU">Начальная страница подписок</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer portal interface: сommon navigation elements</description>
            <description locale="ru_RU">Личный кабинет клиента: общие элементы навигации</description>
        </file>
        <file path="searchform.html" custom="0">
            <description locale="en_US">Search form</description>
            <description locale="ru_RU">Форма поиска</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Mailer app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Рассылки»</description>
        </file>
        <file path="js.html" custom="0">
            <description locale="en_US">JS files (mailer)</description>
            <description locale="ru_RU">JS файлы (рассылки)</description>
        </file>
        <file path="index.html" custom="0" parent="1"></file>
        <file path="error.html" custom="0" parent="1"></file>
    </files>
</theme>

=== slowpokes/webasyst-framework/wa-apps/photos/themes/mobile/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="mobile" system="0" vendor="webasyst" author="Webasyst" app="photos" parent_theme_id="site:mobile" version="1.3.6">
    <name locale="en_US">Mobile</name>
    <name locale="ru_RU">Mobile</name>
    <description locale="ru_RU">Семейство адаптивных тем дизайна.</description>
    <files>
        <file path="album.html" custom="0">
            <description locale="en_US">Wrapper for photo album</description>
            <description locale="ru_RU">Обертка для альбома фотографий</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Photos app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Фото»</description>
        </file>
        <file path="home.html" custom="0">
            <description locale="en_US">Wrapper for the main photo gallery homepage</description>
            <description locale="ru_RU">Обертка для главной страницы фотогалереи</description>
        </file>
        <file path="main.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Photos app content</description>
            <description locale="ru_RU">Основной макет вывода содержимого и навигации в приложении «Фото»</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content</description>
            <description locale="ru_RU">Содержимое информационной страницы</description>
        </file>
        <file path="photo.html" custom="0">
            <description locale="en_US">One photo and its details</description>
            <description locale="ru_RU">Просмотр фотографий по одной</description>
        </file>
        <file path="photos-thumbs.html" custom="0">
            <description locale="en_US">Photo list thumbnails view</description>
            <description locale="ru_RU">Список фотографий эскизами</description>
        </file>
        <file path="photos-plain.html" custom="0">
            <description locale="en_US">Photo list plain view</description>
            <description locale="ru_RU">Список фотографий «простыней»</description>
        </file>
        <file path="search.html" custom="0">
            <description locale="en_US">Wrapper for photo search (filtering) results, e.g. by tag or by rating</description>
            <description locale="ru_RU">Обертка для страницы поиска (фильтрации) фотографий, например, по тегу или автору</description>
        </file>

        <file path="mobile.photos.css" custom="0">
        </file>
        <file path="mobile.photos.js" custom="0">
        </file>

        <file path="error.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="index.html" parent="1">
        </file>
        <file path="layout-head.html" parent="1">
        </file>
        <file path="layout-header.html" parent="1">
        </file>
        <file path="layout-menu.html" parent="1">
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="mobile.css" parent="1">
        </file>
        <file path="mobile.js" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
]]>
    </about>
</theme>
