=== slowpokes/webasyst-framework/wa-content/xml/wa-app-theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT theme (name+,description*,files*,about*, settings?)>
<!ATTLIST theme
	id CDATA #REQUIRED
	system (1|0) "0"
	vendor CDATA #IMPLIED
	author CDATA #IMPLIED
	app CDATA #REQUIRED
	parent_theme_id CDATA #IMPLIED
	version CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	locale CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description
	locale CDATA #REQUIRED
>
<!ELEMENT files (file+)>
<!ELEMENT file (description*)>
<!ATTLIST file
	path CDATA #REQUIRED
	custom (1|0) "0"
	parent (1|0) "0"
>
<!ELEMENT about (#PCDATA)>
<!ATTLIST about
	locale CDATA #REQUIRED
>
<!ELEMENT settings (setting+)>
<!ELEMENT setting (name+,description*,options?)>

<!ATTLIST setting
        var CDATA #REQUIRED
        value CDATA #IMPLIED
        control_type ("text"|"select"|"checkbox") "text"

>
<!ELEMENT options (option+)>
<!ELEMENT option (name*)>
<!ATTLIST option
        value CDATA #IMPLIED
>

=== slowpokes/webasyst-framework/wa-apps/blog/themes/mobile/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="mobile" system="0" vendor="webasyst" author="Webasyst" app="blog" parent_theme_id="site:mobile" version="1.3.6">
    <name locale="en_US">Mobile</name>
    <name locale="ru_RU">Mobile</name>
    <files>
        <file path="head.html" custom="0">
            <description locale="en_US">Blog app's &lt;head&gt; instructions</description>
            <description locale="en_US">Блок &lt;head&gt; приложения «Блог»</description>
        </file>
        <file path="layout-comment.html" custom="0">
        </file>
        <file path="layout-comment-form.html" custom="0">
        </file>
        <file path="layout-comment-list.html" custom="0">
        </file>
        <file path="layout-nav.html" parent="0">
        </file>
        <file path="main.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Blog app content</description>
            <description locale="ru_RU">Основной макет вывода содержимого и навигации в приложении «Блог»</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static info page</description>
            <description locale="ru_RU">Информационная страница</description>
        </file>
        <file path="post.html" custom="0">
            <description locale="en_US">Dedicated post page</description>
            <description locale="ru_RU">Страница одной записи блога</description>
        </file>
        <file path="post.album.html" custom="0">
            <description locale="en_US">Photo album attached to the blog post</description>
            <description locale="ru_RU">Фотоальбом, прикрепленный к записи в блоге</description>
        </file>
        <file path="stream.html" custom="0">
            <description locale="en_US">Post stream wrapper</description>
            <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
        </file>
        <file path="stream_posts.html" custom="0">
            <description locale="en_US">Default post list view mode</description>
            <description locale="ru_RU">Основной вид списка записей блога</description>
        </file>
        <file path="stream_search.html" custom="0">
            <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
            <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
        </file>

        <file path="mobile.blog.css" custom="0">
        </file>
        <file path="mobile.blog.js" custom="0">
        </file>

        <file path="error.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="index.html" parent="1">
        </file>
        <file path="layout-head.html" parent="1">
        </file>
        <file path="layout-header.html" parent="1">
        </file>
        <file path="layout-menu.html" parent="1">
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="mobile.css" parent="1">
        </file>
        <file path="mobile.js" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>Default</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Default theme for the Site application. All Default design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
<p>Default design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p><b>Default</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Default для приложения «Сайт» (данная тема). Все темы дизайна Default для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Default оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>
</theme>

=== slowpokes/webasyst-framework/wa-apps/blog/themes/ascetic/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="ascetic" system="1" vendor="webasyst" author="Webasyst" app="blog" version="1.1.0">
    <name locale="en_US">Ascetic (Default 1.0)</name>
    <name locale="ru_RU">Аскетик (Default 1.0)</name>
    <files>
        <file path="index.html" custom="0">
            <description locale="en_US">Common layout</description>
            <description locale="ru_RU">Основной макет</description>
        </file>
        <file path="ascetic.css">
            <description locale="en_US">Core CSS file</description>
            <description locale="ru_RU">Основной файл CSS-стилей</description>
        </file>
        <file path="mobile.css">
            <description locale="en_US">Additional CSS for multi-touch mobile devices</description>
            <description locale="ru_RU">Дополнительный CSS для мобильных устройств</description>
        </file>
        <file path="sidebar.html" custom="0">
            <description locale="en_US">Blog navigation sidebar</description>
            <description locale="ru_RU">Навигация по блогу</description>
        </file>
        <file path="stream.html" custom="0">
            <description locale="en_US">Post stream wrapper</description>
            <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
        </file>
        <file path="stream_search.html" custom="0">
            <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
            <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
        </file>
        <file path="stream_posts.html" custom="0">
            <description locale="en_US">Default post list view mode</description>
            <description locale="ru_RU">Основной вид списка записей блога</description>
        </file>
        <file path="post.html" custom="0">
            <description locale="en_US">Post page</description>
            <description locale="ru_RU">Страница одной записи блога</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static info page</description>
            <description locale="ru_RU">Информационная страница</description>
        </file>
        <file path="comments.html" custom="0">
            <description locale="en_US">Post comment list</description>
            <description locale="ru_RU">Комментарии к записи блога</description>
        </file>
        <file path="comment.html" custom="0">
            <description locale="en_US">One comment template</description>
            <description locale="ru_RU">Вывод одного комментария из списка</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="blog.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
    </files>
    <settings>
        <setting var="nav_bg_color" control_type="color">
            <value>#000000</value>
            <name locale="en_US">Top navigation menu background color</name>
            <name locale="ru_RU">Цвет фона верхнего навигационного меню</name>
        </setting>
        <setting var="nav_text_color" control_type="color">
            <value>#CCCCCC</value>
            <name locale="en_US">Top navigation menu text color</name>
            <name locale="ru_RU">Цвет ссылок в верхнем навигационном меню</name>
        </setting>
    </settings>
</theme>

=== slowpokes/webasyst-framework/wa-apps/blog/themes/vk/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="vk" system="0" vendor="webasyst" author="Webasyst" app="blog" parent_theme_id="site:vk" version="1.1.0">
    <name locale="en_US">VK</name>
    <name locale="ru_RU">Вконтакте</name>
    <files>
        <file path="index.html" custom="0" parent="1">
        </file>
        <file path="vk.css" custom="0" parent="1">
        </file>
        <file path="vk.js" custom="0" parent="1">
        </file>        
        <file path="vk.blog.css" custom="0">
            <description locale="en_US">Core Blog app CSS</description>
            <description locale="ru_RU">Основной CSS приложения «Блог»</description>
        </file>      
        <file path="content.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Blog app content</description>
            <description locale="ru_RU">Основное макет вывода содержимого и навигации в приложении «Блог»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Blog app's &lt;head&gt; instructions</description>
            <description locale="en_US">Блок &lt;head&gt; приложения «Блог»</description>
        </file>
        <file path="stream.html" custom="0">
            <description locale="en_US">Post stream wrapper</description>
            <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
        </file>
        <file path="stream_search.html" custom="0">
            <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
            <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
        </file>
        <file path="stream_posts.html" custom="0">
            <description locale="en_US">Default post list view mode</description>
            <description locale="ru_RU">Основной вид списка записей блога</description>
        </file>
        <file path="post.html" custom="0">
            <description locale="en_US">Dedicated post page</description>
            <description locale="ru_RU">Страница одной записи блога</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static info page</description>
            <description locale="ru_RU">Информационная страница</description>
        </file>
        <file path="comments.html" custom="0">
            <description locale="en_US">Post comment list</description>
            <description locale="ru_RU">Комментарии к записи блога</description>
        </file>
        <file path="comment.html" custom="0">
            <description locale="en_US">One comment template</description>
            <description locale="ru_RU">Вывод одного комментария из списка</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="navigation.html" custom="0">
            <description locale="en_US">Internal app navigation</description>
            <description locale="ru_RU">Внутренняя навигация приложения</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="searchform.html" custom="0">
            <description locale="en_US">Internal app search form</description>
            <description locale="ru_RU">Форма поиска в приложении</description>
        </file> 
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>VK</b> design themes are designed for embedding Webasyst-powered websites into <a href="http://vk.com">VK.com</a> social network as iframe apps. VK theme family is universal — there is a theme for every basic Webasyst app: Site, Blog, Photos, Shop-Script, etc. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the VK theme for the Site application. All VK design themes for other apps (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p>Темы <b>VK</b> разработаны для внедрения сайтов, созданных на основе фреймворка Вебасист, в соцсеть «<a href="http://vk.com">Вконтакте</a>» в виде iframe-приложений. Семейство тем VK универсальное — подходит для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема для приложения «Сайт». Все темы VK для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
]]>
    </about>    
</theme>
