=== slowpokes/webasyst-framework/wa-content/xml/wa-app-theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT theme (name+,description*,files*,about*, settings?)>
<!ATTLIST theme
	id CDATA #REQUIRED
	system (1|0) "0"
	vendor CDATA #IMPLIED
	author CDATA #IMPLIED
	app CDATA #REQUIRED
	parent_theme_id CDATA #IMPLIED
	version CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	locale CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description
	locale CDATA #REQUIRED
>
<!ELEMENT files (file+)>
<!ELEMENT file (description*)>
<!ATTLIST file
	path CDATA #REQUIRED
	custom (1|0) "0"
	parent (1|0) "0"
>
<!ELEMENT about (#PCDATA)>
<!ATTLIST about
	locale CDATA #REQUIRED
>
<!ELEMENT settings (setting+)>
<!ELEMENT setting (name+,description*,options?)>

<!ATTLIST setting
        var CDATA #REQUIRED
        value CDATA #IMPLIED
        control_type ("text"|"select"|"checkbox") "text"

>
<!ELEMENT options (option+)>
<!ELEMENT option (name*)>
<!ATTLIST option
        value CDATA #IMPLIED
>

=== slowpokes/webasyst-framework/wa-apps/site/themes/sidebar/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="sidebar" system="0" vendor="webasyst" author="Webasyst" app="site" version="1.1.1">
  <name locale="en_US">Sidebar</name>
  <name locale="ru_RU">Sidebar</name>
  <description locale="ru_RU">Семейство адаптивных тем дизайна.</description>
  <files>
    <file path="index.html" custom="0">
		<description locale="en_US">Core layout of the Sidebar theme family</description>
		<description locale="ru_RU">Основной макет тем дизайна семейства Sidebar</description>
    </file>
    <file path="sidebar.css" custom="0">
		<description locale="en_US">Core CSS of the Sidebar theme family</description>
		<description locale="ru_RU">Основной файл CSS-стилей семейства тем дизайна Sidebar</description>
    </file>
    <file path="sidebar.mobile.css" custom="0">
		<description locale="en_US">Additional CSS for multi-touch mobile devices</description>
		<description locale="ru_RU">Дополнительный CSS для мобильных устройств</description>
    </file>
    <file path="sidebar.tablet.css" custom="0">
		<description locale="en_US">Additional CSS for tablet computers (e.g. iPad)</description>
		<description locale="ru_RU">Дополнительный CSS для планшетных компьютеров (например, iPad)</description>
    </file>
    <file path="sidebar.wide.css" custom="0">
		<description locale="en_US">Additional CSS for wide-screen devices</description>
		<description locale="ru_RU">Дополнительный CSS для устройств с широким экраном</description>
    </file>
    <file path="sidebar.js" custom="0">
		<description locale="en_US">JS</description>
		<description locale="ru_RU">JS</description>
    </file>
	<file path="content.html" custom="0">
		<description locale="en_US">Main layout for the Site app content</description>
		<description locale="en_US">Основной вывод приложения «Сайт»</description>
	</file>
	<file path="head.html" custom="0">
		<description locale="en_US">Site app's &lt;head&gt; instructions</description>
		<description locale="en_US">Блок &lt;head&gt; приложения «Сайт»</description>
	</file>
	<file path="footer.html" custom="0">
		<description locale="en_US">App specific footer content</description>
		<description locale="ru_RU">Содержимое футера приложения</description>
    </file>
    <file path="page.html" custom="0">
		<description locale="en_US">Static page content and navigation</description>
		<description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
    </file>
    <file path="login.html" custom="0">
		<description locale="en_US">Login page</description>
		<description locale="ru_RU">Страница входа для пользователей</description>
	</file>
    <file path="signup.html" custom="0">
        <description locale="en_US">Sign up page</description>
        <description locale="ru_RU">Страница регистрации пользователей</description>
    </file>
    <file path="forgotpassword.html" custom="0">
        <description locale="en_US">Forgot password page</description>
        <description locale="ru_RU">Страница сброса пароля</description>
    </file>
    <file path="error.html" custom="0">
		<description locale="en_US">404 and other errors</description>
		<description locale="ru_RU">404 и другие ошибки</description>
    </file>
    <file path="pagelist.html" custom="0">
        <description locale="en_US">Internal app page tree</description>
        <description locale="ru_RU">Внутренняя навигация по информационным страницам приложения</description>
    </file>
  </files>
  <about locale="en_US">
<![CDATA[
<p><b>Sidebar</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Sidebar (i.e. this) theme for the Site application. All Sidebar design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main (i.e. this) theme.</p>
<p>Sidebar design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
  </about>
  <about locale="ru_RU">
<![CDATA[
<p><b>Sidebar</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Sidebar для приложения «Сайт» (данная тема). Все темы дизайна Sidebar для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Sidebar оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
  </about>
</theme>

=== slowpokes/webasyst-framework/wa-apps/blog/themes/dsv2/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="dsv2" system="0" vendor="988467" author="Designsovkusom" app="blog" parent_theme_id="site:dsv2" version="2.5.0">
  <name locale="en_US">Design with taste 2</name>
  <name locale="ru_RU">Дизайн со вкусом 2</name>
  <files>
    <file path="index.html" custom="0" parent="1">
        </file>
    <file path="main.html" custom="0">
      <description locale="en_US">Main layout and navigation for the Blog app content</description>
      <description locale="ru_RU">Основное макет вывода содержимого и навигации в приложении «Блог»</description>
    </file>
    <file path="head.html" custom="0">
      <description locale="en_US">Blog app's &lt;head&gt; instructions</description>
      <description locale="en_US">Блок &lt;head&gt; приложения «Блог»</description>
    </file>
    <file path="js.html" custom="0">
      <description locale="en_US">JS files (blog)</description>
      <description locale="ru_RU">JS файлы (блог)</description>
    </file>
    <file path="sidebar.html" custom="0">
      <description locale="en_US">Sidebar (Blog)</description>
      <description locale="ru_RU">Боковая панель (Блог)</description>
    </file>
    <file path="stream.html" custom="0">
      <description locale="en_US">Post stream wrapper</description>
      <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
    </file>
    <file path="stream_search.html" custom="0">
      <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
      <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
    </file>
    <file path="stream_posts.html" custom="0">
      <description locale="en_US">Default post list view mode</description>
      <description locale="ru_RU"/>
    </file>
    <file path="post.html" custom="0">
      <description locale="en_US">Dedicated post page</description>
      <description locale="ru_RU">Страница одной записи блога</description>
    </file>
    <file path="page.html" custom="0">
      <description locale="en_US">Static info page</description>
      <description locale="ru_RU">Информационная страница</description>
    </file>
    <file path="comments.html" custom="0">
      <description locale="en_US">Post comment list</description>
      <description locale="ru_RU">Комментарии к записи блога</description>
    </file>
    <file path="comment.html" custom="0">
      <description locale="en_US">One comment template</description>
      <description locale="ru_RU">Вывод одного комментария из списка</description>
    </file>
    <file path="footer.html" custom="0">
      <description locale="en_US">App specific footer content</description>
      <description locale="ru_RU">Содержимое футера приложения</description>
    </file>
    <file path="blog.js" custom="0">
      <description locale="en_US">JS</description>
      <description locale="ru_RU">JS</description>
    </file>
    <file path="dsv.blog.css" custom="0">
      <description locale="ru_RU">CSS стили приложения «Блог»</description>
    </file>
    <file path="post.album.html">
      <description locale="en_US">Photo album attached to the blog post</description>
      <description locale="ru_RU">Фотоальбом, прикрепленный к записи в блоге</description>
    </file>
    <file path="menu.app.html" custom="0">
      <description locale="en_US">Blog application menu</description>
      <description locale="ru_RU">Меню приложения Блог</description>
    </file>
    <file path="searchform.html" custom="0">
      <description locale="en_US">Search form</description>
      <description locale="ru_RU">Форма поиска</description>
    </file>
    <file path="dsv.css" custom="0" parent="1">
      <description locale="ru_RU">Базовый набор стилей «Дизайн со вкусом 2»</description>
    </file>
    <file path="bootstrap.min.css" custom="0" parent="1">
      <description locale="ru_RU">Bootstrap v3.2.0</description>
    </file>
    <file path="dsv.css" custom="0" parent="1">
      <description locale="ru_RU">Базовый набор стилей «Дизайн со вкусом 2»</description>
      <description locale="ru_RU">Base styles «Design with taste 2»</description>
    </file>
    <file path="dsv.min.css" custom="0" parent="1">
      <description locale="ru_RU">Базовый набор стилей (минимизированный)</description>
      <description locale="ru_RU">Base styles «Design with taste 2» (compressed)</description>
    </file>
    <file path="font-awesome.min.css" custom="0" parent="1">
      <description locale="ru_RU">Font Awesome 4.3.0</description>
    </file>
    <file path="dsv.js" custom="0" parent="1">
      <description locale="ru_RU">Основной js файл</description>
    </file>
    <file path="login.html" parent="1"/>
    <file path="signup.html" parent="1"/>
    <file path="forgotpassword.html" parent="1"/>
    <file path="my.profile.html" parent="1"/>
    <file path="error.html" parent="1"/>
  </files>
  <about locale="en_US">
&lt;p&gt;&lt;b&gt; «Design with taste» &lt;/b&gt; - is a universal family of those designs for all base application framework WebAsyst: Website, Blog, Photography, Shop-Script and others. Parent (main) theme of family, which includes a basic set of CSS-styles and the overall layout design index.html, is the theme for the application «Design with taste» "Site" (this issue). All themes «Design with taste» design for other applications (Blog, Photo and others) use the base CSS and index.html from the parent (main) theme. &lt;/ p&gt;
&lt;p&gt;&lt;b&gt; «Design with taste» &lt;/b&gt; also adapted and optimized for mobile devices (Pads and Smartphones). Topic is based on Bootstrap 3, which provide correct display on all modern browsers.&lt;/p&gt;

    </about>
  <about locale="ru_RU">
&lt;p&gt;&lt;b&gt; «Дизайн со вкусом» &lt;/b&gt; - это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема «Дизайн со вкусом» для приложения «Сайт». Все темы дизайна шаблона других приложений (Блог, Фото, Магазин и других) используют базовый CSS и index.html из родительской (основной) темы. &lt;/p&gt;
&lt;p&gt;&lt;b&gt; «Дизайн со вкусом» &lt;/b&gt; также адаптирован и оптимизирован для мобильных устройств (планшеты и смартфоны). Тема дизайна разработана на основе Bootstrap 3, что обеспечивает корректное отображение на всех современных браузерах. &lt;/p&gt;

    </about>
  <settings>
    <setting var="divider_blog" control_type="group_divider">
      <value/>
      <name locale="en_US">3.0. Sidebar (Blog)</name>
      <name locale="ru_RU">3.0. Боковая панель (Блог)</name>
    </setting>
    <setting var="divider_sidebar_blog" control_type="group_divider">
      <value/>
      <name locale="en_US">3.1. Sidebar (Blog)</name>
      <name locale="ru_RU">3.1. Боковая панель (Блог)</name>
    </setting>
    <setting var="sidebar_blog_home" control_type="checkbox">
      <value>1</value>
      <name locale="en_US">Homepage</name>
      <name locale="ru_RU">Главная страница</name>
    </setting>
    <setting var="sidebar_blog_post" control_type="checkbox">
      <value>1</value>
      <name locale="en_US">Post page</name>
      <name locale="ru_RU">Страница поста</name>
    </setting>
  </settings>
</theme>

=== slowpokes/webasyst-framework/wa-apps/blog/themes/sidebar/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="sidebar" system="0" vendor="webasyst" author="Webasyst" app="blog" parent_theme_id="site:sidebar" version="2.0.0">
    <name locale="en_US">Sidebar 2.0</name>
    <name locale="ru_RU">Sidebar 2.0</name>
    <files>
        <file path="index.html" custom="0" parent="1">
        </file>
        <file path="sidebar.css" custom="0" parent="1">
        </file>
        <file path="sidebar.blog.css" custom="0">
            <description locale="en_US">Core Blog app CSS</description>
            <description locale="ru_RU">Основной CSS приложения «Блог»</description>
        </file>      
        <file path="sidebar.blog.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
        <file path="main.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Blog app content</description>
            <description locale="ru_RU">Основное макет вывода содержимого и навигации в приложении «Блог»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Blog app's &lt;head&gt; instructions</description>
            <description locale="en_US">Блок &lt;head&gt; приложения «Блог»</description>
        </file>
        <file path="stream.html" custom="0">
            <description locale="en_US">Post stream wrapper</description>
            <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
        </file>
        <file path="stream_search.html" custom="0">
            <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
            <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
        </file>
        <file path="stream_posts.html" custom="0">
            <description locale="en_US">Default post list view mode</description>
            <description locale="ru_RU">Основной вид списка записей блога</description>
        </file>
        <file path="post.html" custom="0">
            <description locale="en_US">Dedicated post page</description>
            <description locale="ru_RU">Страница одной записи блога</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static info page</description>
            <description locale="ru_RU">Информационная страница</description>
        </file>
        <file path="comments.html" custom="0">
            <description locale="en_US">Post comment list</description>
            <description locale="ru_RU">Комментарии к записи блога</description>
        </file>
        <file path="comment.html" custom="0">
            <description locale="en_US">One comment template</description>
            <description locale="ru_RU">Вывод одного комментария из списка</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="nav.sidebar.html" custom="0">
            <description locale="en_US">Internal app navigation tree</description>
            <description locale="ru_RU">Внутренняя навигация приложения</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="error.html" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>Sidebar</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Sidebar theme for the Site application. All Sidebar design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
<p>Sidebar design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p><b>Sidebar</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Sidebar для приложения «Сайт» (данная тема). Все темы дизайна Sidebar для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Sidebar оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>    
</theme>

=== slowpokes/webasyst-framework/wa-apps/blog/themes/designsovkusom/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="designsovkusom" system="0" vendor="bd9" author="zVadim" app="blog" parent_theme_id="site:designsovkusom" version="1.1.0">
    <name locale="en_US">designsovkusom</name>
    <name locale="ru_RU">designsovkusom</name>
    <files>
        <file path="index.html" custom="0" parent="1">
        </file>
        <file path="dsv.menu.html" custom="0" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
]]>
    </about>    
</theme>

=== slowpokes/webasyst-framework/wa-apps/blog/themes/mmtt/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="mmtt" system="0" vendor="bd9" author="Vadim" app="blog" parent_theme_id="site:mmtt" version="1.1.0">
    <name locale="en_US">mmtt</name>
    <name locale="ru_RU">mmtt</name>
    <files>
        <file path="index.html" custom="0" parent="1">
        </file>
        <file path="header.html" custom="0" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
]]>
    </about>    
</theme>

=== slowpokes/webasyst-framework/wa-apps/photos/themes/ascetic/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="ascetic" system="1" vendor="webasyst" author="Webasyst" app="photos" version="1.1.0">
    <name locale="en_US">Ascetic (Default 1.0)</name>
    <name locale="ru_RU">Аскетик (Default 1.0)</name>
    <files>
        <file path="index.html" custom="0">
            <description locale="en_US">Common layout</description>
            <description locale="ru_RU">Основной макет</description>
        </file>
        <file path="ascetic.css" custom="0">
            <description locale="en_US">Core CSS file</description>
            <description locale="ru_RU">Основной файл CSS-стилей</description>
        </file>
        <file path="mobile.css" custom="0">
            <description locale="en_US">Additional CSS for multi-touch mobile devices</description>
            <description locale="ru_RU">Дополнительный CSS для мобильных устройств</description>
        </file>        
        <file path="view-thumbs.html" custom="0">
            <description locale="en_US">Photo thumbnail list view</description>
            <description locale="ru_RU">Список фотографий эскизами</description>
        </file>
        <file path="view-plain.html" custom="0">
            <description locale="en_US">Photo plain list view</description>
            <description locale="ru_RU">Список фотографий «простыней»</description>
        </file>
        <file path="photo.html" custom="0">
            <description locale="en_US">One photo and its details</description>
            <description locale="ru_RU">Просмотр фотографий по одной</description>
        </file>
        <file path="home.html" custom="0">
            <description locale="en_US">Wrapper for the main photo gallery homepage</description>
            <description locale="ru_RU">Обертка для главной страницы фотогалереи</description>
        </file>
        <file path="album.html" custom="0">
            <description locale="en_US">Wrapper for photo album</description>
            <description locale="ru_RU">Обертка для альбома фотографий</description>
        </file>
        <file path="search.html" custom="0">
            <description locale="en_US">Wrapper for photo search (filtering) results, e.g. by tag or by rating</description>
            <description locale="ru_RU">Обертка для страницы поиска (фильтрации) фотографий, например, по тегу или автору</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content</description>
            <description locale="ru_RU">Содержимое информационной страницы</description>
        </file>
        <file path="sidebar.html" custom="0">
            <description locale="en_US">Navigation sidebar</description>
              <description locale="ru_RU">Колонка с навигацией по фотогалерее</description>
        </file>
        <file path="login.html">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="error.html">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="lazyloading.js">
            <description locale="en_US">Lazy loading JS</description>
            <description locale="ru_RU">Скрипты загрузки контента «на лету»</description>
        </file>
    </files>
    <settings>
        <setting var="nav_bg_color" control_type="color">
            <value>#000000</value>
            <name locale="en_US">Top navigation menu background color</name>
            <name locale="ru_RU">Цвет фона верхнего навигационного меню</name>
        </setting>
        <setting var="nav_text_color" control_type="color">
            <value>#CCCCCC</value>
            <name locale="en_US">Top navigation menu text color</name>
            <name locale="ru_RU">Цвет ссылок в верхнем навигационном меню</name>
        </setting>
    </settings>
    <thumbs>
        <thumb>200x0</thumb>
        <thumb>970</thumb>
    </thumbs>
</theme>
